export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Home } from './Home'
export { default as Admin } from './Admin'
export { default as Product } from './Admin/Product'
export { default as Categories } from './Admin/Product/Categories'